### ISSUE TITLE
How to have a "page" that is accessible only via its URL?

### ISSUE THREAD

**Issue by ondrejsojka** [enten/hyde-y#16]
My client requires me to have an interresting links page, but they don't want to list in on the front page, only in the lefthand menu.

**Comment by enten** [comment]
The lefthand menu ([partials/bloc/header/nav.html](https://github.com/enten/hyde-y/blob/master/layouts/partials/bloc/header/nav.html)) is composed by two modules : 
- [partials/bloc/header/nav_primary.html](https://github.com/enten/hyde-y/blob/master/layouts/partials/bloc/header/nav_primary.html)
  - includes [modules/site/link/home.html](https://github.com/enten/hyde-y/blob/master/layouts/partials/modules/site/link/home.html) which show the home link
  - includes [modules/site/link/menu.html](https://github.com/enten/hyde-y/blob/master/layouts/partials/modules/site/link/menu.html) which show menu links which is declared into data/Menu ([example here](https://github.com/enten/hugo-boilerplate/blob/master/data/Menu.toml)) 
- [paritals/bloc/header/nav_secondary.html](https://github.com/enten/hyde-y/blob/master/layouts/partials/bloc/header/nav_secondary.html) :
  - includes [modules/site/link/social.html](https://github.com/enten/hyde-y/blob/master/layouts/partials/modules/site/link/social.html) which show social links

**Can you try to create content/links.md and test http://baseurl/links url? I think that your page will be shown but won't be listed in the lefthand menu (because no link entry was added into data/Menu).**

**Comment by ondrejsojka** [comment]
I'm sorry for not expressing exactly, but I wanted to **not** have the page listed in the list of all articles. By list of all articles I mean the list you get when you visit https://baseurl/ I will add it to the lefthand menu manually.

**Comment by enten** [comment]
The homepage module ([partials/homepage.html](https://github.com/enten/hyde-y/blob/master/layouts/partials/homepage.html)) list all page with type "post".

To do what you want:
- create a new [section](https://gohugo.io/content/sections/) titled "homepages" for exemple (new directory named "homapges" into "content" folder)
- override partials/homepage.html by creating homepage.html under the folder layouts/partials into your hugo project
- copy and past the code of the original [partials/homepage.html](https://github.com/enten/hyde-y/blob/master/layouts/partials/homepage.html) and change the ["where" filter](https://gohugo.io/templates/list#where) to list pages into "homepages" section: <code> {{ $paginator := .Paginate (where .Data.Pages "Section" "homespages") }}</code>

With this configuration, ONLY posts into the "homepages" section will be shown on the homepage.

**Comment by ondrejsojka** [comment]
Great, all I needed was to change the type in my markdown/toml files from post to something else. Their placement in folders in the content directory doesn't matter.

**Comment by enten** [comment]
Thanks for this advice.
