### ISSUE TITLE
Google Analytics issues

### ISSUE THREAD

**Issue by ghost** [enten/hyde-y#36]
Hi - I can't seem to get GA working on my site.  I've tried all kinds of things from stackoverflow, but can't seem to resolve it.  My repository is here https://github.com/emmamclarnon1/garden and my blogsite https://gardenr.netlify.com/  Is there anything I can do to get it to work? 

Many thanks,

Emma

**Comment by enten** [comment]
The GA pageview event is fired by a piece of code declared in [themes/hyde-y/layouts/partials/head.html](https://github.com/enten/hyde-y/blob/5c627acf4ea13e20916b310bc99ee899ed6703e9/layouts/partials/head.html#L12):

```html
  {{ with .Site.Params.googleAnalytics }}
	<script>
	  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
	  ga('create', '{{ . }}', 'auto');
	  ga('send', 'pageview');
	</script>
  {{ end }}
```

I saw in your [config.toml](https://github.com/emmamclarnon1/garden/blob/master/config.toml) that you set `params.googleAnalytics` correctly.

Normally, that should work.

But when I cheked your blogsite I don't find the right code.

I looked quickly your repository and it don't match with your blogsite source code. I also saw that you did customization. I think that there are some issues due to your change. The main is the bad submodule reference to the hyde-y repository.

I'm sorry but I haven't the time to instigate your code. May you can easily restart from scratch your blogsite by using [enten/hugo-boilerplate](https://github.com/enten/hugo-boilerplate) and copy/past your documents and setups?

**Comment by ghost** [comment]
Thank you -  I downloaded the whole Hyde-y repository and replaced all my old files in hyde-y with these ones from the repository.  It has only partially worked.  It picked me up on GA but immediately stopped working.  It should work with the new hyde-y files without me having to change any settings in the themes file, right?

**Comment by enten** [comment]
You're welcome but you fixed your issue alone :smile:
